"""Run nozzle sizing, a motor/nozzle burn, and flight from one TOML input.

Run from the repository root after installing PyRocket:
    python examples/nozzle_to_flight.py --output-dir outputs/nozzle-to-flight
"""
import argparse
import json
import math
from pathlib import Path

import PyRocket


def write_config(path, motor, flight=None):
    """Write the flat scalar tables used by this example."""
    lines = ['# Generated by examples/nozzle_to_flight.py', 'version = 1']
    for name, parameters in [('simulation', motor), ('flight', flight)]:
        if parameters is None:
            continue
        lines.extend(['', f'[{name}]'])
        for key, value in parameters.items():
            if type(value) not in {int, float, bool, str}:
                raise ValueError(f'{name}.{key} must be numeric, boolean, or a string')
            lines.append(f'{key} = {json.dumps(value, allow_nan=False)}')
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def run_workflow(input_path, output_dir, plots=True):
    config = PyRocket.load(input_path)
    if config.simulation is None or config.flight is None:
        raise ValueError('workflow requires both [simulation] and [flight]')
    design_entry = config.calculations.get('nozzle_design', {})
    if design_entry.get('type') != 'nozzle':
        raise ValueError('workflow requires a nozzle calculation named nozzle_design')
    output_dir = Path(output_dir)
    products = ['nozzle.json', 'motor.json', 'flight.json', 'motor.toml', 'flight.toml',
                'thrust.png', 'pressure.png', 'altitude.png', 'trajectory.png']
    if any((output_dir / name).resolve() in config.protected_paths() for name in products):
        raise ValueError('workflow output must differ from input files')

    # 1. Size the ideal nozzle at the configured design point.
    design = PyRocket.run(config, 'nozzle_design')
    geometry = design['result']
    parameters = design_entry['parameters']
    motor_parameters = dict(config.simulation)
    motor_parameters.update(
        throat_radius_m=math.sqrt(geometry['throat_area_m2'] / math.pi),
        exit_area_m2=geometry['exit_area_m2'],
        characteristic_velocity_m_s=geometry['characteristic_velocity_m_s'],
        gamma=parameters['gamma'], ambient_pressure_pa=parameters['ambient_pressure'])

    # 2. Simulate the designed nozzle as part of the motor through burnout.
    motor = {'calculation': 'simulation',
             'result': PyRocket.propulsion.simulate(**motor_parameters)}
    if not motor['result']['summary']['completed']:
        raise ValueError('motor must reach burnout before flight; increase its run limits')

    # 3. Consume exactly that computed thrust and mass history in flight.
    trajectory = {'calculation': 'flight', 'result': PyRocket.flight.simulate(
        **config.flight, motor_history=motor['result']['history'])}
    trajectory['result']['motor'] = motor['result']

    output_dir.mkdir(parents=True, exist_ok=True)
    write_config(output_dir / 'motor.toml', motor_parameters)
    write_config(output_dir / 'flight.toml', motor_parameters, config.flight)
    for filename, response in [('nozzle.json', design), ('motor.json', motor), ('flight.json', trajectory)]:
        (output_dir / filename).write_text(json.dumps(response, indent=2, allow_nan=False) + '\n', encoding='utf-8')
    if plots:
        for response, filename, field in [(motor, 'thrust.png', 'thrust_n'),
                                          (motor, 'pressure.png', 'chamber_pressure_pa'),
                                          (trajectory, 'altitude.png', 'altitude_m'),
                                          (trajectory, 'trajectory.png', 'trajectory')]:
            PyRocket.plot(response, output_dir / filename, field)
    return {'nozzle': design, 'motor': motor, 'flight': trajectory}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', type=Path, default=Path(__file__).with_name('nozzle-to-flight.toml'))
    parser.add_argument('--output-dir', type=Path, default=Path('outputs/nozzle-to-flight'))
    parser.add_argument('--no-plots', action='store_true', help='Run without Matplotlib')
    args = parser.parse_args(argv)
    try:
        result = run_workflow(args.config, args.output_dir, not args.no_plots)
    except (OSError, ValueError, ArithmeticError) as exc:
        parser.error(str(exc))
    print(f'Wrote workflow outputs to {args.output_dir}')
    print(json.dumps({'motor': result['motor']['result']['summary'],
                      'flight': result['flight']['result']['summary']}, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
